#!/bin/bash
#
# run all installers

set -e

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
  echo "› ${installer}..."
  bash -c "$installer"
done
